services:
  - name: ytbuddy1-server
    type: web
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000

  - name: ytbuddy1-client
    type: web
    runtime: node
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: VITE_API_URL
        value: https://ytbuddy1-server.onrender.com